name: Test and deploy

on:
 push:
   branches: [ main ]

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2

     - name: Install NodeJS
       uses: actions/setup-node@v1

     - name: Install packages
       run: npm i

     - name: Run unit tests with Jest
       run: npm run test
